# ‚è±Ô∏èü•± Students that took too long are removed ‚ùå

In [7]:
import pandas as pd
import numpy as np



point5= pd.read_csv('5point.csv',delimiter=';')
point5.head(100)
# Pivot the DataFrame based on 'idll_vo3lv', and 'timestamp', with 'name' as columns and 'value' as values
pivot_df = pd.pivot_table(point5, 
                          index=[ 'idll_vo3lv', 'timestamp'], 
                          columns='name', 
                          values='value', 
                          aggfunc=lambda x: x).reset_index()

# drop the rows with NaN values in timestampload column and the row below it
pivot_df = pivot_df.dropna(subset=['timestampload'], axis=0).reset_index(drop=True)

# group the pivot_df by studentid and get the first and last row of each group
first_last_df = pivot_df.groupby('idll_vo3lv').apply(lambda x: x.iloc[[0,-1]])
first_last_df.reset_index(drop=True, inplace=True)

# group the pivot_df by studentid and calculate the time difference between consecutive rows
grouped_df = pivot_df.groupby('idll_vo3lv')['timestamp'].apply(lambda x: pd.to_datetime(x).diff().dt.total_seconds())
# filter the resulting dataframe to keep only the rows where the time difference is greater than 180 seconds
result_df = grouped_df[grouped_df > 180].reset_index()

unique_student_ids = result_df['idll_vo3lv'].unique().tolist()
print("We have ", len(unique_student_ids), " Students who took longer than 180 seconds")
pivot_df = pivot_df[~pivot_df['idll_vo3lv'].isin(unique_student_ids)]

print("And ", pivot_df['idll_vo3lv'].nunique(), " Students left")
pd.set_option('display.max_rows', 100)
pivot_df.head(50)

C:\Users\ASU_M1603QAMB046W\AppData\Local\Temp\ipykernel_15604\1218651984.py:23: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  grouped_df = pivot_df.groupby('idll_vo3lv')['timestamp'].apply(lambda x: pd.to_datetime(x).diff().dt.total_seconds())

We have  193  Students who took longer than 180 seconds
And  4358  Students left

name,idll_vo3lv,timestamp,numbercl,patternsm,statuscl,timestampcl,timestampload,timestampsm
12,2,2020-10-01 09:52:14,"1,6,8,4,5,7,2,7,7,3","1,1,1,1,1,1,1,1","1,1,1,1,1,1,1,0,1,1","1601538723165,1601538724144,1601538725021,1601...",1601538721805,12106
13,2,2020-10-01 09:52:31,"6,8,4,1,2,7,8,5,8","1,1,0,1,1,1,1,1","1,1,1,1,1,1,0,1,1","1601538737663,1601538738454,1601538739815,1601...",1601538734066,17061
14,2,2020-10-01 09:52:40,"4,5,6,2","0,1,0,1,1,1,0,0","1,1,1,1","1601538755645,1601538756591,1601538757392,1601...",1601538751289,8516
15,2,2020-10-01 09:52:52,"3,8,7,5,5,8,5,6,8","0,0,1,0,1,1,1,1","1,1,1,1,0,0,1,1,1","1601538764144,1601538765306,1601538766035,1601...",1601538759972,12023
16,2,2020-10-01 09:52:58,"4,3,2,1","1,1,1,1,0,0,0,0","1,1,1,1","1601538773414,1601538774162,1601538775421,1601...",1601538772148,5470
17,2,2020-10-01 09:53:10,"8,7,6,2,3,3,3","0,1,1,0,0,1,1,1","1,1,1,1,1,0,1","1601538781442,1601538782939,1601538787197,1601...",1601538777799,12570
18,2,2020-10-01 09:53:16,"4,8,6,1,5","1,0,0,1,1,1,0,1","1,1,1,1,1","1601538791574,1601538792319,1601538793102,1601...",1601538790537,5034
19,2,2020-10-01 09:53:23,"7,3,2","0,1,1,0,0,0,1,0","1,1,1","1601538798418,1601538800316,1601538801321",1601538795840,7318
20,2,2020-10-01 09:53:28,"4,5,1","1,0,0,1,1,0,0,0","1,1,1","1601538805275,1601538806172,1601538807063",1601538803499,4793
21,2,2020-10-01 09:53:31,"8,6","0,0,0,0,0,1,0,1","1,1","1601538809428,1601538810415",1601538808458,2799
22,2,2020-10-01 09:53:39,"3,7,2,5,4,1","1,1,1,1,1,0,1,0","1,1,1,1,1,1","1601538812126,1601538812743,1601538813498,1601...",1601538811443,7813
23,2,2020-10-01 09:53:46,NaN,NaN,NaN,"1601538820309,1601538821197,1601538821861,1601...",1601538819467,NaN
24,2,2020-10-01 09:53:47,3,"0,0,1,0,0,0,0,0",1,1601538826435,1601538825694,1414
25,2,2020-10-01 09:53:49,7,"0,0,0,0,0,0,1,0",1,1601538828162,1601538827461,1498
26,2,2020-10-01 09:53:52,"[2, 2]","[0,1,0,0,0,0,0,0, 0,1,0,0,0,0,0,0]","[1, 1]","[1601538829928, 1601538829928]","[1601538829295, 1601538829295]","[2209, 2257]"
27,2,2020-10-01 09:53:59,8,"0,0,0,0,0,0,0,1",1,1601538832575,1601538831818,6712
28,2,2020-10-01 09:54:05,"6,3,3","0,0,0,0,0,1,0,0","1,1,0","1601538840305,1601538841370,1601538844020",1601538838784,6000
29,2,2020-10-01 09:54:08,"4,4,4","0,0,0,1,0,0,0,0","1,0,1","1601538845916,1601538845972,1601538846915",1601538844987,2889
30,2,2020-10-01 09:54:11,5,"0,0,0,0,1,0,0,0",1,1601538849579,1601538848323,2485
31,2,2020-10-01 09:54:14,1,"1,0,0,0,0,0,0,0",1,1601538852212,1601538851054,2966
32,2,2020-10-01 09:54:18,"5,7","0,0,0,0,1,0,1,0","1,1","1601538855845,1601538856887",1601538854280,3641
33,2,2020-10-01 09:54:22,"8,6","0,0,0,0,0,1,0,1","1,1","1601538860269,1601538861148",1601538858174,4136
34,2,2020-10-01 09:54:34,"1,3","1,0,1,0,0,0,0,0","1,1","1601538871202,1601538872759",1601538862573,11111
35,2,2020-10-01 09:54:38,"4,2","0,1,0,1,0,0,0,0","1,1","1601538875133,1601538876345",1601538873978,3438
36,2,2020-10-01 09:54:43,"8,7","0,0,0,0,0,0,1,1","1,1","1601538880678,1601538881468",1601538877718,5124
37,2,2020-10-01 09:54:49,"5,6","0,0,0,0,1,1,0,0","1,1","1601538884645,1601538885396",1601538883125,5422
38,2,2020-10-01 09:55:36,"4,1,2","1,1,0,1,0,0,0,0","1,1,1","1601538920982,1601538922686,1601538928204",1601538888820,44538
39,3,2020-03-10 12:01:09,"8,3","0,0,1,0,0,0,0,1","1,1","1583838068262,1583838069022",1583838066741,2970
40,3,2020-03-10 12:01:12,"6,1","1,0,0,0,0,1,0,0","1,1","1583838070926,1583838071430",1583838069787,2676
41,3,2020-03-10 12:01:15,"2,8","0,1,0,0,0,0,0,1","1,1","1583838073750,1583838074870",1583838072547,3115
42,3,2020-03-10 12:01:18,"4,5","0,0,0,1,1,0,0,0","1,1","1583838076598,1583838077046",1583838075754,2316
43,3,2020-03-10 12:01:21,"1,6","1,0,0,0,0,1,0,0","1,1","1583838079334,1583838080590",1583838078172,3730
44,3,2020-03-10 12:01:26,"5,7","0,0,0,0,1,0,1,0","1,1","1583838084934,1583838085694",1583838082005,4497
45,3,2020-03-10 12:01:29,"6,3","0,0,1,0,0,1,0,0","1,1","1583838087926,1583838088862",1583838086614,3064
46,3,2020-03-10 12:01:32,"4,5","0,0,0,1,1,0,0,0","1,1","1583838090886,1583838091390",1583838089766,2440
47,3,2020-03-10 12:01:35,"2,8","0,1,0,0,0,0,0,1","1,1","1583838093150,1583838094598",1583838092319,2895
48,3,2020-03-10 12:01:39,"1,3","1,0,1,0,0,0,0,0","1,1","1583838098046,1583838098845",1583838095342,3888
49,3,2020-03-10 12:01:43,"2,4","0,1,0,1,0,0,0,0","1,1","1583838101317,1583838102149",1583838099345,3749
50,3,2020-03-10 12:01:46,"5,6","0,0,0,0,1,1,0,0","1,1","1583838104750,1583838105581",1583838103201,3077
51,3,2020-03-10 12:01:50,"1,6","1,0,0,0,0,1,0,0","1,1","1583838108581,1583838109325",1583838106389,3729
52,3,2020-03-10 12:01:54,"2,4","0,1,0,1,0,0,0,0","1,1","1583838110893,1583838113597",1583838110241,4565
53,3,2020-03-10 12:01:59,"1,5,3,7","1,0,1,0,1,0,1,0","1,1,1,1","1583838115933,1583838116645,1583838118341,1583...",1583838114932,4826
54,3,2020-03-10 12:02:09,"2,4,8,6,8,7,8,5","0,1,0,1,1,1,1,1","1,1,1,1,0,1,1,1","1583838120957,1583838122645,1583838123733,1583...",1583838119901,9080
55,3,2020-03-10 12:02:13,"3,8,1,6,5","1,0,1,0,1,1,0,1","1,1,1,1,1","1583838129589,1583838130397,1583838131268,1583...",1583838129094,4655
56,3,2020-03-10 12:02:16,"2,8,5","0,1,0,0,1,0,0,1","1,1,1","1583838134725,1583838135309,1583838136245",1583838133937,2948
57,3,2020-03-10 12:02:25,"6,4,5,1,3,7,2","1,1,1,1,1,1,1,0","1,1,1,1,1,1,1","1583838138445,1583838139620,1583838140381,1583...",1583838137018,8027
58,3,2020-03-10 12:02:34,"8,8,4,5,1,6,2,3,7,8","1,1,1,1,1,1,1,1","1,0,1,1,1,1,1,1,1,1","1583838146060,1583838146716,1583838147428,1583...",1583838145183,9150
59,3,2020-03-10 12:02:36,"6,5","0,0,0,0,1,1,0,0","1,1","1583838155332,1583838156124",1583838154488,2388
60,3,2020-03-10 12:02:40,"1,2,6,7","1,1,0,0,0,1,1,0","1,1,1,1","1583838157692,1583838158348,1583838158820,1583...",1583838157058,3082
61,3,2020-03-10 12:02:43,"3,8,5,7","0,0,1,0,1,0,1,1","1,1,1,1","1583838160892,1583838161412,1583838161924,1583...",1583838160291,2705

# Defining the strategies:
1. d.a.c. : Click as many times as possible
2. Rotation: make 1 firgure, rotate it 4 times, next figure
3. Subpar: Does not understand the objective at hand M
4. Additive: Add 1 more line to your figure untill it is completely filled
5. substractive: Remove 1 line until you have 1 or 0 left
6. Single: click 1 line until all 8 lines make 8 different figures M

## ‚öîÔ∏è 1. Devide and Conquer ‚öîÔ∏è
The student just submitted a lot of **CORRECT** answers very quickly less than 2.5 seconds per figure.

In [3]:
#code here

## üîÅ 2. Rotation üîÅ
The student chose **1** figure, rotated that 4 times and moved on to the next figure to do the same.

In [4]:
#code here

## 3. ü§™ Subpar: Does not understand the objective at hand ü§™
A lot of the same figure, a lot of clicks with no real results, very long time between figures etc.

In [5]:
def identify_strategy(actions):
    # Check if the value is a float or NaN
    if isinstance(actions, (float, int)):
        return "Invalid"  # Handle NaN or unexpected numeric values
    elif actions is None:
        return "Missing"  # Handle None or missing values
    else:
        unique_values = len(set(actions))
        if unique_values <= 2:
            return "Subpar"
        else:
            return "Advanced"
 #Apply the identify_strategy function to the 'numbercl' column and create a new 'strategy' column
pivot_df['strategy'] = pivot_df['numbercl'].apply(lambda x: identify_strategy(x))
pivot_df.head(50)

name,idll_vo3lv,timestamp,numbercl,patternsm,statuscl,timestampcl,timestampload,timestampsm,strategy
12,2,2020-10-01 09:52:14,"1,6,8,4,5,7,2,7,7,3","1,1,1,1,1,1,1,1","1,1,1,1,1,1,1,0,1,1","1601538723165,1601538724144,1601538725021,1601...",1601538721805,12106,Advanced
13,2,2020-10-01 09:52:31,"6,8,4,1,2,7,8,5,8","1,1,0,1,1,1,1,1","1,1,1,1,1,1,0,1,1","1601538737663,1601538738454,1601538739815,1601...",1601538734066,17061,Advanced
14,2,2020-10-01 09:52:40,"4,5,6,2","0,1,0,1,1,1,0,0","1,1,1,1","1601538755645,1601538756591,1601538757392,1601...",1601538751289,8516,Advanced
15,2,2020-10-01 09:52:52,"3,8,7,5,5,8,5,6,8","0,0,1,0,1,1,1,1","1,1,1,1,0,0,1,1,1","1601538764144,1601538765306,1601538766035,1601...",1601538759972,12023,Advanced
16,2,2020-10-01 09:52:58,"4,3,2,1","1,1,1,1,0,0,0,0","1,1,1,1","1601538773414,1601538774162,1601538775421,1601...",1601538772148,5470,Advanced
17,2,2020-10-01 09:53:10,"8,7,6,2,3,3,3","0,1,1,0,0,1,1,1","1,1,1,1,1,0,1","1601538781442,1601538782939,1601538787197,1601...",1601538777799,12570,Advanced
18,2,2020-10-01 09:53:16,"4,8,6,1,5","1,0,0,1,1,1,0,1","1,1,1,1,1","1601538791574,1601538792319,1601538793102,1601...",1601538790537,5034,Advanced
19,2,2020-10-01 09:53:23,"7,3,2","0,1,1,0,0,0,1,0","1,1,1","1601538798418,1601538800316,1601538801321",1601538795840,7318,Advanced
20,2,2020-10-01 09:53:28,"4,5,1","1,0,0,1,1,0,0,0","1,1,1","1601538805275,1601538806172,1601538807063",1601538803499,4793,Advanced
21,2,2020-10-01 09:53:31,"8,6","0,0,0,0,0,1,0,1","1,1","1601538809428,1601538810415",1601538808458,2799,Advanced
22,2,2020-10-01 09:53:39,"3,7,2,5,4,1","1,1,1,1,1,0,1,0","1,1,1,1,1,1","1601538812126,1601538812743,1601538813498,1601...",1601538811443,7813,Advanced
23,2,2020-10-01 09:53:46,NaN,NaN,NaN,"1601538820309,1601538821197,1601538821861,1601...",1601538819467,NaN,Invalid
24,2,2020-10-01 09:53:47,3,"0,0,1,0,0,0,0,0",1,1601538826435,1601538825694,1414,Subpar
25,2,2020-10-01 09:53:49,7,"0,0,0,0,0,0,1,0",1,1601538828162,1601538827461,1498,Subpar
26,2,2020-10-01 09:53:52,"[2, 2]","[0,1,0,0,0,0,0,0, 0,1,0,0,0,0,0,0]","[1, 1]","[1601538829928, 1601538829928]","[1601538829295, 1601538829295]","[2209, 2257]",Subpar
27,2,2020-10-01 09:53:59,8,"0,0,0,0,0,0,0,1",1,1601538832575,1601538831818,6712,Subpar
28,2,2020-10-01 09:54:05,"6,3,3","0,0,0,0,0,1,0,0","1,1,0","1601538840305,1601538841370,1601538844020",1601538838784,6000,Advanced
29,2,2020-10-01 09:54:08,"4,4,4","0,0,0,1,0,0,0,0","1,0,1","1601538845916,1601538845972,1601538846915",1601538844987,2889,Subpar
30,2,2020-10-01 09:54:11,5,"0,0,0,0,1,0,0,0",1,1601538849579,1601538848323,2485,Subpar
31,2,2020-10-01 09:54:14,1,"1,0,0,0,0,0,0,0",1,1601538852212,1601538851054,2966,Subpar
32,2,2020-10-01 09:54:18,"5,7","0,0,0,0,1,0,1,0","1,1","1601538855845,1601538856887",1601538854280,3641,Advanced
33,2,2020-10-01 09:54:22,"8,6","0,0,0,0,0,1,0,1","1,1","1601538860269,1601538861148",1601538858174,4136,Advanced
34,2,2020-10-01 09:54:34,"1,3","1,0,1,0,0,0,0,0","1,1","1601538871202,1601538872759",1601538862573,11111,Advanced
35,2,2020-10-01 09:54:38,"4,2","0,1,0,1,0,0,0,0","1,1","1601538875133,1601538876345",1601538873978,3438,Advanced
36,2,2020-10-01 09:54:43,"8,7","0,0,0,0,0,0,1,1","1,1","1601538880678,1601538881468",1601538877718,5124,Advanced
37,2,2020-10-01 09:54:49,"5,6","0,0,0,0,1,1,0,0","1,1","1601538884645,1601538885396",1601538883125,5422,Advanced
38,2,2020-10-01 09:55:36,"4,1,2","1,1,0,1,0,0,0,0","1,1,1","1601538920982,1601538922686,1601538928204",1601538888820,44538,Advanced
39,3,2020-03-10 12:01:09,"8,3","0,0,1,0,0,0,0,1","1,1","1583838068262,1583838069022",1583838066741,2970,Advanced
40,3,2020-03-10 12:01:12,"6,1","1,0,0,0,0,1,0,0","1,1","1583838070926,1583838071430",1583838069787,2676,Advanced
41,3,2020-03-10 12:01:15,"2,8","0,1,0,0,0,0,0,1","1,1","1583838073750,1583838074870",1583838072547,3115,Advanced
42,3,2020-03-10 12:01:18,"4,5","0,0,0,1,1,0,0,0","1,1","1583838076598,1583838077046",1583838075754,2316,Advanced
43,3,2020-03-10 12:01:21,"1,6","1,0,0,0,0,1,0,0","1,1","1583838079334,1583838080590",1583838078172,3730,Advanced
44,3,2020-03-10 12:01:26,"5,7","0,0,0,0,1,0,1,0","1,1","1583838084934,1583838085694",1583838082005,4497,Advanced
45,3,2020-03-10 12:01:29,"6,3","0,0,1,0,0,1,0,0","1,1","1583838087926,1583838088862",1583838086614,3064,Advanced
46,3,2020-03-10 12:01:32,"4,5","0,0,0,1,1,0,0,0","1,1","1583838090886,1583838091390",1583838089766,2440,Advanced
47,3,2020-03-10 12:01:35,"2,8","0,1,0,0,0,0,0,1","1,1","1583838093150,1583838094598",1583838092319,2895,Advanced
48,3,2020-03-10 12:01:39,"1,3","1,0,1,0,0,0,0,0","1,1","1583838098046,1583838098845",1583838095342,3888,Advanced
49,3,2020-03-10 12:01:43,"2,4","0,1,0,1,0,0,0,0","1,1","1583838101317,1583838102149",1583838099345,3749,Advanced
50,3,2020-03-10 12:01:46,"5,6","0,0,0,0,1,1,0,0","1,1","1583838104750,1583838105581",1583838103201,3077,Advanced
51,3,2020-03-10 12:01:50,"1,6","1,0,0,0,0,1,0,0","1,1","1583838108581,1583838109325",1583838106389,3729,Advanced
52,3,2020-03-10 12:01:54,"2,4","0,1,0,1,0,0,0,0","1,1","1583838110893,1583838113597",1583838110241,4565,Advanced
53,3,2020-03-10 12:01:59,"1,5,3,7","1,0,1,0,1,0,1,0","1,1,1,1","1583838115933,1583838116645,1583838118341,1583...",1583838114932,4826,Advanced
54,3,2020-03-10 12:02:09,"2,4,8,6,8,7,8,5","0,1,0,1,1,1,1,1","1,1,1,1,0,1,1,1","1583838120957,1583838122645,1583838123733,1583...",1583838119901,9080,Advanced
55,3,2020-03-10 12:02:13,"3,8,1,6,5","1,0,1,0,1,1,0,1","1,1,1,1,1","1583838129589,1583838130397,1583838131268,1583...",1583838129094,4655,Advanced
56,3,2020-03-10 12:02:16,"2,8,5","0,1,0,0,1,0,0,1","1,1,1","1583838134725,1583838135309,1583838136245",1583838133937,2948,Advanced
57,3,2020-03-10 12:02:25,"6,4,5,1,3,7,2","1,1,1,1,1,1,1,0","1,1,1,1,1,1,1","1583838138445,1583838139620,1583838140381,1583...",1583838137018,8027,Advanced
58,3,2020-03-10 12:02:34,"8,8,4,5,1,6,2,3,7,8","1,1,1,1,1,1,1,1","1,0,1,1,1,1,1,1,1,1","1583838146060,1583838146716,1583838147428,1583...",1583838145183,9150,Advanced
59,3,2020-03-10 12:02:36,"6,5","0,0,0,0,1,1,0,0","1,1","1583838155332,1583838156124",1583838154488,2388,Advanced
60,3,2020-03-10 12:02:40,"1,2,6,7","1,1,0,0,0,1,1,0","1,1,1,1","1583838157692,1583838158348,1583838158820,1583...",1583838157058,3082,Advanced
61,3,2020-03-10 12:02:43,"3,8,5,7","0,0,1,0,1,0,1,1","1,1,1,1","1583838160892,1583838161412,1583838161924,1583...",1583838160291,2705,Advanced

## ‚ûï 4. Additive: Add 1 more line to your figure untill it is completely filled ‚ûï
start with one line and add moe and more untill your figure is completely filled

## ‚ûñ 5. substractive: Remove 1 line until you have 1 or 0 left ‚ûñ
Start with a complec figure and remove lines untill there is 1 or none left.

## ü¶Ü-d 6. Single: click 1 line until all 8 lines make 8 different figures 1Ô∏è üê≠
Different figures with one line each

In [12]:
import pandas as pd
import numpy as np

# Function to parse 'patternsm' column
def parse_patternsm(x):
    return list(map(int, x.split(','))) if pd.notna(x) else []

# Function to check if all figures are unique in a list
def has_unique_figures(lst):
    return len(set(lst)) == len(lst)

# Function to check if all elements in the arrays are the same
def all_elements_same(arr):
    return all(x == arr[0] for x in arr)

# Function to identify strategy
def identify_strategy(row):
    pattern_list = parse_patternsm(row['patternsm'])
    number_array = np.array(list(map(int, row['numbercl'].split(',')))) if pd.notna(row['numbercl']) else []
    status_array = np.array(list(map(int, row['statuscl'].split(',')))) if pd.notna(row['statuscl']) else []
    timestamp_array = np.array(list(map(int, row['timestampcl'].split(',')))) if pd.notna(row['timestampcl']) else []

    if has_unique_figures(pattern_list):
        if all_elements_same(number_array) and all_elements_same(status_array) and all_elements_same(timestamp_array):
            return 'Single: click 1 line until all 8 lines make 8 different figures'
        else:
            return 'Unique Figures'
    else:
        return 'Not Unique Figures'

# Apply the strategy identification function to create a 'Strategy' column
pivot_df['Strategy'] = pivot_df.apply(identify_strategy, axis=1)

# Displaying the DataFrame with the new 'Strategy' column
print(pivot_df[['idll_vo3lv', 'patternsm', 'Strategy']])

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()