# ‚è±Ô∏èü•± Students that took too long are removed ‚ùå

In [26]:
import pandas as pd
import numpy as np

# 1. Read in the data
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
df = pd.read_csv('Ozdb_fivepoints_vo3_2019-2020_vo4_2020-2021.csv', delimiter=';')

pivot_df = pd.pivot_table(df, index=[ 'idll_vo3lv', 'timestamp'], columns='name', values='value', aggfunc=lambda x: x).reset_index()
print("We started with ", pivot_df['idll_vo3lv'].nunique(), " students")

# drop the rows with NaN values in timestampload column and the row below it
pivot_df = pivot_df.dropna(subset=['timestampload'], axis=0).reset_index(drop=True)

# group the pivot_df by idll_vo3lv and get the first and last row of each group
first_last_df = pivot_df.groupby('idll_vo3lv').apply(lambda x: x.iloc[[0,-1]])
first_last_df.reset_index(drop=True, inplace=True)

# group the pivot_df by idll_vo3lv and calculate the time difference between consecutive rows
grouped_df = pivot_df.groupby('idll_vo3lv')['timestamp'].apply(lambda x: pd.to_datetime(x).diff().dt.total_seconds())
# filter the resulting dataframe to keep only the rows where the time difference is greater than 180 seconds
result_df = grouped_df[grouped_df > 180].reset_index()

unique_student_ids = result_df['idll_vo3lv'].unique().tolist()
print("We have ", len(unique_student_ids), " Students who took longer than 180 seconds")
pivot_df = pivot_df[~pivot_df['idll_vo3lv'].isin(unique_student_ids)]

print("And ", pivot_df['idll_vo3lv'].nunique(), " Students left")

Dataset = pivot_df
Dataset['patternsm'] = Dataset['patternsm'].astype(str)
Dataset.head(75)

We started with  4551  students

C:\Users\ASU_M1603QAMB046W\AppData\Local\Temp\ipykernel_12380\288799604.py:20: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  grouped_df = pivot_df.groupby('idll_vo3lv')['timestamp'].apply(lambda x: pd.to_datetime(x).diff().dt.total_seconds())

We have  193  Students who took longer than 180 seconds
And  4358  Students left

name,idll_vo3lv,timestamp,numbercl,patternsm,statuscl,timestampcl,timestampload,timestampsm
12,2,2020-10-01 09:52:14,"1,6,8,4,5,7,2,7,7,3","1,1,1,1,1,1,1,1","1,1,1,1,1,1,1,0,1,1","1601538723165,1601538724144,1601538725021,1601...",1601538721805,12106
13,2,2020-10-01 09:52:31,"6,8,4,1,2,7,8,5,8","1,1,0,1,1,1,1,1","1,1,1,1,1,1,0,1,1","1601538737663,1601538738454,1601538739815,1601...",1601538734066,17061
14,2,2020-10-01 09:52:40,"4,5,6,2","0,1,0,1,1,1,0,0","1,1,1,1","1601538755645,1601538756591,1601538757392,1601...",1601538751289,8516
15,2,2020-10-01 09:52:52,"3,8,7,5,5,8,5,6,8","0,0,1,0,1,1,1,1","1,1,1,1,0,0,1,1,1","1601538764144,1601538765306,1601538766035,1601...",1601538759972,12023
16,2,2020-10-01 09:52:58,"4,3,2,1","1,1,1,1,0,0,0,0","1,1,1,1","1601538773414,1601538774162,1601538775421,1601...",1601538772148,5470
17,2,2020-10-01 09:53:10,"8,7,6,2,3,3,3","0,1,1,0,0,1,1,1","1,1,1,1,1,0,1","1601538781442,1601538782939,1601538787197,1601...",1601538777799,12570
18,2,2020-10-01 09:53:16,"4,8,6,1,5","1,0,0,1,1,1,0,1","1,1,1,1,1","1601538791574,1601538792319,1601538793102,1601...",1601538790537,5034
19,2,2020-10-01 09:53:23,"7,3,2","0,1,1,0,0,0,1,0","1,1,1","1601538798418,1601538800316,1601538801321",1601538795840,7318
20,2,2020-10-01 09:53:28,"4,5,1","1,0,0,1,1,0,0,0","1,1,1","1601538805275,1601538806172,1601538807063",1601538803499,4793
21,2,2020-10-01 09:53:31,"8,6","0,0,0,0,0,1,0,1","1,1","1601538809428,1601538810415",1601538808458,2799
22,2,2020-10-01 09:53:39,"3,7,2,5,4,1","1,1,1,1,1,0,1,0","1,1,1,1,1,1","1601538812126,1601538812743,1601538813498,1601...",1601538811443,7813
23,2,2020-10-01 09:53:46,NaN,nan,NaN,"1601538820309,1601538821197,1601538821861,1601...",1601538819467,NaN
24,2,2020-10-01 09:53:47,3,"0,0,1,0,0,0,0,0",1,1601538826435,1601538825694,1414
25,2,2020-10-01 09:53:49,7,"0,0,0,0,0,0,1,0",1,1601538828162,1601538827461,1498
26,2,2020-10-01 09:53:52,"[2, 2]","['0,1,0,0,0,0,0,0' '0,1,0,0,0,0,0,0']","[1, 1]","[1601538829928, 1601538829928]","[1601538829295, 1601538829295]","[2209, 2257]"
27,2,2020-10-01 09:53:59,8,"0,0,0,0,0,0,0,1",1,1601538832575,1601538831818,6712
28,2,2020-10-01 09:54:05,"6,3,3","0,0,0,0,0,1,0,0","1,1,0","1601538840305,1601538841370,1601538844020",1601538838784,6000
29,2,2020-10-01 09:54:08,"4,4,4","0,0,0,1,0,0,0,0","1,0,1","1601538845916,1601538845972,1601538846915",1601538844987,2889
30,2,2020-10-01 09:54:11,5,"0,0,0,0,1,0,0,0",1,1601538849579,1601538848323,2485
31,2,2020-10-01 09:54:14,1,"1,0,0,0,0,0,0,0",1,1601538852212,1601538851054,2966
32,2,2020-10-01 09:54:18,"5,7","0,0,0,0,1,0,1,0","1,1","1601538855845,1601538856887",1601538854280,3641
33,2,2020-10-01 09:54:22,"8,6","0,0,0,0,0,1,0,1","1,1","1601538860269,1601538861148",1601538858174,4136
34,2,2020-10-01 09:54:34,"1,3","1,0,1,0,0,0,0,0","1,1","1601538871202,1601538872759",1601538862573,11111
35,2,2020-10-01 09:54:38,"4,2","0,1,0,1,0,0,0,0","1,1","1601538875133,1601538876345",1601538873978,3438
36,2,2020-10-01 09:54:43,"8,7","0,0,0,0,0,0,1,1","1,1","1601538880678,1601538881468",1601538877718,5124
37,2,2020-10-01 09:54:49,"5,6","0,0,0,0,1,1,0,0","1,1","1601538884645,1601538885396",1601538883125,5422
38,2,2020-10-01 09:55:36,"4,1,2","1,1,0,1,0,0,0,0","1,1,1","1601538920982,1601538922686,1601538928204",1601538888820,44538
39,3,2020-03-10 12:01:09,"8,3","0,0,1,0,0,0,0,1","1,1","1583838068262,1583838069022",1583838066741,2970
40,3,2020-03-10 12:01:12,"6,1","1,0,0,0,0,1,0,0","1,1","1583838070926,1583838071430",1583838069787,2676
41,3,2020-03-10 12:01:15,"2,8","0,1,0,0,0,0,0,1","1,1","1583838073750,1583838074870",1583838072547,3115
42,3,2020-03-10 12:01:18,"4,5","0,0,0,1,1,0,0,0","1,1","1583838076598,1583838077046",1583838075754,2316
43,3,2020-03-10 12:01:21,"1,6","1,0,0,0,0,1,0,0","1,1","1583838079334,1583838080590",1583838078172,3730
44,3,2020-03-10 12:01:26,"5,7","0,0,0,0,1,0,1,0","1,1","1583838084934,1583838085694",1583838082005,4497
45,3,2020-03-10 12:01:29,"6,3","0,0,1,0,0,1,0,0","1,1","1583838087926,1583838088862",1583838086614,3064
46,3,2020-03-10 12:01:32,"4,5","0,0,0,1,1,0,0,0","1,1","1583838090886,1583838091390",1583838089766,2440
47,3,2020-03-10 12:01:35,"2,8","0,1,0,0,0,0,0,1","1,1","1583838093150,1583838094598",1583838092319,2895
48,3,2020-03-10 12:01:39,"1,3","1,0,1,0,0,0,0,0","1,1","1583838098046,1583838098845",1583838095342,3888
49,3,2020-03-10 12:01:43,"2,4","0,1,0,1,0,0,0,0","1,1","1583838101317,1583838102149",1583838099345,3749
50,3,2020-03-10 12:01:46,"5,6","0,0,0,0,1,1,0,0","1,1","1583838104750,1583838105581",1583838103201,3077
51,3,2020-03-10 12:01:50,"1,6","1,0,0,0,0,1,0,0","1,1","1583838108581,1583838109325",1583838106389,3729
52,3,2020-03-10 12:01:54,"2,4","0,1,0,1,0,0,0,0","1,1","1583838110893,1583838113597",1583838110241,4565
53,3,2020-03-10 12:01:59,"1,5,3,7","1,0,1,0,1,0,1,0","1,1,1,1","1583838115933,1583838116645,1583838118341,1583...",1583838114932,4826
54,3,2020-03-10 12:02:09,"2,4,8,6,8,7,8,5","0,1,0,1,1,1,1,1","1,1,1,1,0,1,1,1","1583838120957,1583838122645,1583838123733,1583...",1583838119901,9080
55,3,2020-03-10 12:02:13,"3,8,1,6,5","1,0,1,0,1,1,0,1","1,1,1,1,1","1583838129589,1583838130397,1583838131268,1583...",1583838129094,4655
56,3,2020-03-10 12:02:16,"2,8,5","0,1,0,0,1,0,0,1","1,1,1","1583838134725,1583838135309,1583838136245",1583838133937,2948
57,3,2020-03-10 12:02:25,"6,4,5,1,3,7,2","1,1,1,1,1,1,1,0","1,1,1,1,1,1,1","1583838138445,1583838139620,1583838140381,1583...",1583838137018,8027
58,3,2020-03-10 12:02:34,"8,8,4,5,1,6,2,3,7,8","1,1,1,1,1,1,1,1","1,0,1,1,1,1,1,1,1,1","1583838146060,1583838146716,1583838147428,1583...",1583838145183,9150
59,3,2020-03-10 12:02:36,"6,5","0,0,0,0,1,1,0,0","1,1","1583838155332,1583838156124",1583838154488,2388
60,3,2020-03-10 12:02:40,"1,2,6,7","1,1,0,0,0,1,1,0","1,1,1,1","1583838157692,1583838158348,1583838158820,1583...",1583838157058,3082
61,3,2020-03-10 12:02:43,"3,8,5,7","0,0,1,0,1,0,1,1","1,1,1,1","1583838160892,1583838161412,1583838161924,1583...",1583838160291,2705
62,3,2020-03-10 12:02:47,"6,1,5,4,3","1,0,1,1,1,1,0,0","1,1,1,1,1","1583838163716,1583838164268,1583838164852,1583...",1583838163148,4608
63,3,2020-03-10 12:02:51,"7,8,2,6","0,1,0,0,0,1,1,1","1,1,1,1","1583838168620,1583838169219,1583838170012,1583...",1583838167918,3862
64,3,2020-03-10 12:02:56,"1,3,8,5","1,0,1,0,1,0,0,1","1,1,1,1","1583838172939,1583838174380,1583838174956,1583...",1583838171937,4235
65,3,2020-03-10 12:03:01,"6,7,4,5,2","0,1,0,1,1,1,1,0","1,1,1,1,1","1583838176908,1583838177531,1583838178867,1583...",1583838176349,5287
66,3,2020-03-10 12:03:04,"1,6","1,0,0,0,0,1,0,0","1,1","1583838182692,1583838183267",1583838181877,2327
67,3,2020-03-10 12:03:09,"3,8,6,7","0,0,1,0,0,1,1,1","1,1,1,1","1583838186427,1583838187051,1583838187451,1583...",1583838184388,4600
68,3,2020-03-10 12:03:14,"1,5,2","1,1,0,0,1,0,0,0","1,1,1","1583838190211,1583838190851,1583838193387",1583838189182,4797
69,3,2020-03-10 12:03:16,"7,6","0,0,0,0,0,1,1,0","1,1","1583838194507,1583838195059",1583838194206,1894
70,3,2020-03-10 12:03:18,"3,7","0,0,1,0,0,0,1,0","1,1","1583838196755,1583838197275",1583838196292,1743
71,3,2020-03-10 12:03:23,"8,6,7,8,8,4","0,0,0,1,0,1,1,1","1,1,1,0,1,1","1583838199003,1583838199523,1583838200051,1583...",1583838198226,5137
72,3,2020-03-10 12:03:27,"3,7,2,6","0,1,1,0,0,1,1,0","1,1,1,1","1583838204179,1583838204987,1583838205571,1583...",1583838203551,3812
73,3,2020-03-10 12:03:31,"1,5,7","1,0,0,0,1,0,1,0","1,1,1","1583838208307,1583838208970,1583838210163",1583838207563,3408
74,3,2020-03-10 12:03:34,"3,7,2","0,1,1,0,0,0,1,0","1,1,1","1583838211859,1583838212715,1583838213339",1583838211435,2760
75,3,2020-03-10 12:03:37,"6,8,4","0,0,0,1,0,1,0,1","1,1,1","1583838214907,1583838216171,1583838216587",1583838214418,2817
76,3,2020-03-10 12:03:42,"1,3,2,4","1,1,1,1,0,0,0,0","1,1,1,1","1583838218371,1583838219995,1583838220939,1583...",1583838217461,5173
77,3,2020-03-10 12:03:46,"7,5,1","1,0,0,0,1,0,1,0","1,1,1","1583838223474,1583838224794,1583838225626",1583838222893,3702
78,3,2020-03-10 12:03:50,"3,2,8","0,1,1,0,0,0,0,1","1,1,1","1583838227523,1583838228226,1583838229521",1583838226819,3463
79,3,2020-03-10 12:03:55,"1,6,6,6","1,0,0,0,0,1,0,0","1,1,0,1","1583838231258,1583838231858,1583838233265,1583...",1583838230515,5200
80,3,2020-03-10 12:03:57,NaN,"0,0,0,0,0,0,0,0",NaN,NaN,1583838235961,850
81,3,2020-03-10 12:04:00,3,"0,0,1,0,0,0,0,0",1,1583838238226,1583838237140,2958
82,3,2020-03-10 12:04:02,4,"0,0,0,1,0,0,0,0",1,1583838241434,1583838240385,1889
83,3,2020-03-10 12:04:04,2,"0,1,0,0,0,0,0,0",1,1583838243249,1583838242509,1645
84,3,2020-03-10 12:04:09,"7,6,2,7,3","0,1,1,0,0,1,0,0","1,1,1,0,1","1583838244922,1583838245698,1583838246441,1583...",1583838244450,4880
85,3,2020-03-10 12:04:13,"8,1,6,2","1,1,0,0,0,1,0,1","1,1,1,1","1583838250738,1583838251505,1583838252146,1583...",1583838249573,3869
86,3,2020-03-10 12:04:17,"8,4,5","0,0,0,1,1,0,0,1","1,1,1","1583838254802,1583838255649,1583838256394",1583838253707,3823

In [21]:
def convert_binary_string(input_string):
    binary_list = input_string.split(',')
    result_list = []
    for i, bit in enumerate(binary_list):
        if bit == 'nan':
            result_list.append('0')
        elif bit == "['0'":
            result_list.append('0')
        else:
            try:
                result_list.append(str(i + 1) if int(bit) == 1 else '0')
            except ValueError:
                result_list.append('0')
    result_string = ','.join(result_list)
    return result_string

Dataset['new_column'] = Dataset['patternsm'].apply(convert_binary_string)
Dataset.head(75)

name,idll_vo3lv,timestamp,numbercl,patternsm,statuscl,timestampcl,timestampload,timestampsm,new_column
12,2,2020-10-01 09:52:14,"1,6,8,4,5,7,2,7,7,3","1,1,1,1,1,1,1,1","1,1,1,1,1,1,1,0,1,1","1601538723165,1601538724144,1601538725021,1601...",1601538721805,12106,"1,2,3,4,5,6,7,8"
13,2,2020-10-01 09:52:31,"6,8,4,1,2,7,8,5,8","1,1,0,1,1,1,1,1","1,1,1,1,1,1,0,1,1","1601538737663,1601538738454,1601538739815,1601...",1601538734066,17061,"1,2,0,4,5,6,7,8"
14,2,2020-10-01 09:52:40,"4,5,6,2","0,1,0,1,1,1,0,0","1,1,1,1","1601538755645,1601538756591,1601538757392,1601...",1601538751289,8516,"0,2,0,4,5,6,0,0"
15,2,2020-10-01 09:52:52,"3,8,7,5,5,8,5,6,8","0,0,1,0,1,1,1,1","1,1,1,1,0,0,1,1,1","1601538764144,1601538765306,1601538766035,1601...",1601538759972,12023,"0,0,3,0,5,6,7,8"
16,2,2020-10-01 09:52:58,"4,3,2,1","1,1,1,1,0,0,0,0","1,1,1,1","1601538773414,1601538774162,1601538775421,1601...",1601538772148,5470,"1,2,3,4,0,0,0,0"
17,2,2020-10-01 09:53:10,"8,7,6,2,3,3,3","0,1,1,0,0,1,1,1","1,1,1,1,1,0,1","1601538781442,1601538782939,1601538787197,1601...",1601538777799,12570,"0,2,3,0,0,6,7,8"
18,2,2020-10-01 09:53:16,"4,8,6,1,5","1,0,0,1,1,1,0,1","1,1,1,1,1","1601538791574,1601538792319,1601538793102,1601...",1601538790537,5034,"1,0,0,4,5,6,0,8"
19,2,2020-10-01 09:53:23,"7,3,2","0,1,1,0,0,0,1,0","1,1,1","1601538798418,1601538800316,1601538801321",1601538795840,7318,"0,2,3,0,0,0,7,0"
20,2,2020-10-01 09:53:28,"4,5,1","1,0,0,1,1,0,0,0","1,1,1","1601538805275,1601538806172,1601538807063",1601538803499,4793,"1,0,0,4,5,0,0,0"
21,2,2020-10-01 09:53:31,"8,6","0,0,0,0,0,1,0,1","1,1","1601538809428,1601538810415",1601538808458,2799,"0,0,0,0,0,6,0,8"
22,2,2020-10-01 09:53:39,"3,7,2,5,4,1","1,1,1,1,1,0,1,0","1,1,1,1,1,1","1601538812126,1601538812743,1601538813498,1601...",1601538811443,7813,"1,2,3,4,5,0,7,0"
23,2,2020-10-01 09:53:46,NaN,nan,NaN,"1601538820309,1601538821197,1601538821861,1601...",1601538819467,NaN,0
24,2,2020-10-01 09:53:47,3,"0,0,1,0,0,0,0,0",1,1601538826435,1601538825694,1414,"0,0,3,0,0,0,0,0"
25,2,2020-10-01 09:53:49,7,"0,0,0,0,0,0,1,0",1,1601538828162,1601538827461,1498,"0,0,0,0,0,0,7,0"
26,2,2020-10-01 09:53:52,"[2, 2]","['0,1,0,0,0,0,0,0' '0,1,0,0,0,0,0,0']","[1, 1]","[1601538829928, 1601538829928]","[1601538829295, 1601538829295]","[2209, 2257]","0,2,0,0,0,0,0,0,9,0,0,0,0,0,0"
27,2,2020-10-01 09:53:59,8,"0,0,0,0,0,0,0,1",1,1601538832575,1601538831818,6712,"0,0,0,0,0,0,0,8"
28,2,2020-10-01 09:54:05,"6,3,3","0,0,0,0,0,1,0,0","1,1,0","1601538840305,1601538841370,1601538844020",1601538838784,6000,"0,0,0,0,0,6,0,0"
29,2,2020-10-01 09:54:08,"4,4,4","0,0,0,1,0,0,0,0","1,0,1","1601538845916,1601538845972,1601538846915",1601538844987,2889,"0,0,0,4,0,0,0,0"
30,2,2020-10-01 09:54:11,5,"0,0,0,0,1,0,0,0",1,1601538849579,1601538848323,2485,"0,0,0,0,5,0,0,0"
31,2,2020-10-01 09:54:14,1,"1,0,0,0,0,0,0,0",1,1601538852212,1601538851054,2966,"1,0,0,0,0,0,0,0"
32,2,2020-10-01 09:54:18,"5,7","0,0,0,0,1,0,1,0","1,1","1601538855845,1601538856887",1601538854280,3641,"0,0,0,0,5,0,7,0"
33,2,2020-10-01 09:54:22,"8,6","0,0,0,0,0,1,0,1","1,1","1601538860269,1601538861148",1601538858174,4136,"0,0,0,0,0,6,0,8"
34,2,2020-10-01 09:54:34,"1,3","1,0,1,0,0,0,0,0","1,1","1601538871202,1601538872759",1601538862573,11111,"1,0,3,0,0,0,0,0"
35,2,2020-10-01 09:54:38,"4,2","0,1,0,1,0,0,0,0","1,1","1601538875133,1601538876345",1601538873978,3438,"0,2,0,4,0,0,0,0"
36,2,2020-10-01 09:54:43,"8,7","0,0,0,0,0,0,1,1","1,1","1601538880678,1601538881468",1601538877718,5124,"0,0,0,0,0,0,7,8"
37,2,2020-10-01 09:54:49,"5,6","0,0,0,0,1,1,0,0","1,1","1601538884645,1601538885396",1601538883125,5422,"0,0,0,0,5,6,0,0"
38,2,2020-10-01 09:55:36,"4,1,2","1,1,0,1,0,0,0,0","1,1,1","1601538920982,1601538922686,1601538928204",1601538888820,44538,"1,2,0,4,0,0,0,0"
39,3,2020-03-10 12:01:09,"8,3","0,0,1,0,0,0,0,1","1,1","1583838068262,1583838069022",1583838066741,2970,"0,0,3,0,0,0,0,8"
40,3,2020-03-10 12:01:12,"6,1","1,0,0,0,0,1,0,0","1,1","1583838070926,1583838071430",1583838069787,2676,"1,0,0,0,0,6,0,0"
41,3,2020-03-10 12:01:15,"2,8","0,1,0,0,0,0,0,1","1,1","1583838073750,1583838074870",1583838072547,3115,"0,2,0,0,0,0,0,8"
42,3,2020-03-10 12:01:18,"4,5","0,0,0,1,1,0,0,0","1,1","1583838076598,1583838077046",1583838075754,2316,"0,0,0,4,5,0,0,0"
43,3,2020-03-10 12:01:21,"1,6","1,0,0,0,0,1,0,0","1,1","1583838079334,1583838080590",1583838078172,3730,"1,0,0,0,0,6,0,0"
44,3,2020-03-10 12:01:26,"5,7","0,0,0,0,1,0,1,0","1,1","1583838084934,1583838085694",1583838082005,4497,"0,0,0,0,5,0,7,0"
45,3,2020-03-10 12:01:29,"6,3","0,0,1,0,0,1,0,0","1,1","1583838087926,1583838088862",1583838086614,3064,"0,0,3,0,0,6,0,0"
46,3,2020-03-10 12:01:32,"4,5","0,0,0,1,1,0,0,0","1,1","1583838090886,1583838091390",1583838089766,2440,"0,0,0,4,5,0,0,0"
47,3,2020-03-10 12:01:35,"2,8","0,1,0,0,0,0,0,1","1,1","1583838093150,1583838094598",1583838092319,2895,"0,2,0,0,0,0,0,8"
48,3,2020-03-10 12:01:39,"1,3","1,0,1,0,0,0,0,0","1,1","1583838098046,1583838098845",1583838095342,3888,"1,0,3,0,0,0,0,0"
49,3,2020-03-10 12:01:43,"2,4","0,1,0,1,0,0,0,0","1,1","1583838101317,1583838102149",1583838099345,3749,"0,2,0,4,0,0,0,0"
50,3,2020-03-10 12:01:46,"5,6","0,0,0,0,1,1,0,0","1,1","1583838104750,1583838105581",1583838103201,3077,"0,0,0,0,5,6,0,0"
51,3,2020-03-10 12:01:50,"1,6","1,0,0,0,0,1,0,0","1,1","1583838108581,1583838109325",1583838106389,3729,"1,0,0,0,0,6,0,0"
52,3,2020-03-10 12:01:54,"2,4","0,1,0,1,0,0,0,0","1,1","1583838110893,1583838113597",1583838110241,4565,"0,2,0,4,0,0,0,0"
53,3,2020-03-10 12:01:59,"1,5,3,7","1,0,1,0,1,0,1,0","1,1,1,1","1583838115933,1583838116645,1583838118341,1583...",1583838114932,4826,"1,0,3,0,5,0,7,0"
54,3,2020-03-10 12:02:09,"2,4,8,6,8,7,8,5","0,1,0,1,1,1,1,1","1,1,1,1,0,1,1,1","1583838120957,1583838122645,1583838123733,1583...",1583838119901,9080,"0,2,0,4,5,6,7,8"
55,3,2020-03-10 12:02:13,"3,8,1,6,5","1,0,1,0,1,1,0,1","1,1,1,1,1","1583838129589,1583838130397,1583838131268,1583...",1583838129094,4655,"1,0,3,0,5,6,0,8"
56,3,2020-03-10 12:02:16,"2,8,5","0,1,0,0,1,0,0,1","1,1,1","1583838134725,1583838135309,1583838136245",1583838133937,2948,"0,2,0,0,5,0,0,8"
57,3,2020-03-10 12:02:25,"6,4,5,1,3,7,2","1,1,1,1,1,1,1,0","1,1,1,1,1,1,1","1583838138445,1583838139620,1583838140381,1583...",1583838137018,8027,"1,2,3,4,5,6,7,0"
58,3,2020-03-10 12:02:34,"8,8,4,5,1,6,2,3,7,8","1,1,1,1,1,1,1,1","1,0,1,1,1,1,1,1,1,1","1583838146060,1583838146716,1583838147428,1583...",1583838145183,9150,"1,2,3,4,5,6,7,8"
59,3,2020-03-10 12:02:36,"6,5","0,0,0,0,1,1,0,0","1,1","1583838155332,1583838156124",1583838154488,2388,"0,0,0,0,5,6,0,0"
60,3,2020-03-10 12:02:40,"1,2,6,7","1,1,0,0,0,1,1,0","1,1,1,1","1583838157692,1583838158348,1583838158820,1583...",1583838157058,3082,"1,2,0,0,0,6,7,0"
61,3,2020-03-10 12:02:43,"3,8,5,7","0,0,1,0,1,0,1,1","1,1,1,1","1583838160892,1583838161412,1583838161924,1583...",1583838160291,2705,"0,0,3,0,5,0,7,8"
62,3,2020-03-10 12:02:47,"6,1,5,4,3","1,0,1,1,1,1,0,0","1,1,1,1,1","1583838163716,1583838164268,1583838164852,1583...",1583838163148,4608,"1,0,3,4,5,6,0,0"
63,3,2020-03-10 12:02:51,"7,8,2,6","0,1,0,0,0,1,1,1","1,1,1,1","1583838168620,1583838169219,1583838170012,1583...",1583838167918,3862,"0,2,0,0,0,6,7,8"
64,3,2020-03-10 12:02:56,"1,3,8,5","1,0,1,0,1,0,0,1","1,1,1,1","1583838172939,1583838174380,1583838174956,1583...",1583838171937,4235,"1,0,3,0,5,0,0,8"
65,3,2020-03-10 12:03:01,"6,7,4,5,2","0,1,0,1,1,1,1,0","1,1,1,1,1","1583838176908,1583838177531,1583838178867,1583...",1583838176349,5287,"0,2,0,4,5,6,7,0"
66,3,2020-03-10 12:03:04,"1,6","1,0,0,0,0,1,0,0","1,1","1583838182692,1583838183267",1583838181877,2327,"1,0,0,0,0,6,0,0"
67,3,2020-03-10 12:03:09,"3,8,6,7","0,0,1,0,0,1,1,1","1,1,1,1","1583838186427,1583838187051,1583838187451,1583...",1583838184388,4600,"0,0,3,0,0,6,7,8"
68,3,2020-03-10 12:03:14,"1,5,2","1,1,0,0,1,0,0,0","1,1,1","1583838190211,1583838190851,1583838193387",1583838189182,4797,"1,2,0,0,5,0,0,0"
69,3,2020-03-10 12:03:16,"7,6","0,0,0,0,0,1,1,0","1,1","1583838194507,1583838195059",1583838194206,1894,"0,0,0,0,0,6,7,0"
70,3,2020-03-10 12:03:18,"3,7","0,0,1,0,0,0,1,0","1,1","1583838196755,1583838197275",1583838196292,1743,"0,0,3,0,0,0,7,0"
71,3,2020-03-10 12:03:23,"8,6,7,8,8,4","0,0,0,1,0,1,1,1","1,1,1,0,1,1","1583838199003,1583838199523,1583838200051,1583...",1583838198226,5137,"0,0,0,4,0,6,7,8"
72,3,2020-03-10 12:03:27,"3,7,2,6","0,1,1,0,0,1,1,0","1,1,1,1","1583838204179,1583838204987,1583838205571,1583...",1583838203551,3812,"0,2,3,0,0,6,7,0"
73,3,2020-03-10 12:03:31,"1,5,7","1,0,0,0,1,0,1,0","1,1,1","1583838208307,1583838208970,1583838210163",1583838207563,3408,"1,0,0,0,5,0,7,0"
74,3,2020-03-10 12:03:34,"3,7,2","0,1,1,0,0,0,1,0","1,1,1","1583838211859,1583838212715,1583838213339",1583838211435,2760,"0,2,3,0,0,0,7,0"
75,3,2020-03-10 12:03:37,"6,8,4","0,0,0,1,0,1,0,1","1,1,1","1583838214907,1583838216171,1583838216587",1583838214418,2817,"0,0,0,4,0,6,0,8"
76,3,2020-03-10 12:03:42,"1,3,2,4","1,1,1,1,0,0,0,0","1,1,1,1","1583838218371,1583838219995,1583838220939,1583...",1583838217461,5173,"1,2,3,4,0,0,0,0"
77,3,2020-03-10 12:03:46,"7,5,1","1,0,0,0,1,0,1,0","1,1,1","1583838223474,1583838224794,1583838225626",1583838222893,3702,"1,0,0,0,5,0,7,0"
78,3,2020-03-10 12:03:50,"3,2,8","0,1,1,0,0,0,0,1","1,1,1","1583838227523,1583838228226,1583838229521",1583838226819,3463,"0,2,3,0,0,0,0,8"
79,3,2020-03-10 12:03:55,"1,6,6,6","1,0,0,0,0,1,0,0","1,1,0,1","1583838231258,1583838231858,1583838233265,1583...",1583838230515,5200,"1,0,0,0,0,6,0,0"
80,3,2020-03-10 12:03:57,NaN,"0,0,0,0,0,0,0,0",NaN,NaN,1583838235961,850,"0,0,0,0,0,0,0,0"
81,3,2020-03-10 12:04:00,3,"0,0,1,0,0,0,0,0",1,1583838238226,1583838237140,2958,"0,0,3,0,0,0,0,0"
82,3,2020-03-10 12:04:02,4,"0,0,0,1,0,0,0,0",1,1583838241434,1583838240385,1889,"0,0,0,4,0,0,0,0"
83,3,2020-03-10 12:04:04,2,"0,1,0,0,0,0,0,0",1,1583838243249,1583838242509,1645,"0,2,0,0,0,0,0,0"
84,3,2020-03-10 12:04:09,"7,6,2,7,3","0,1,1,0,0,1,0,0","1,1,1,0,1","1583838244922,1583838245698,1583838246441,1583...",1583838244450,4880,"0,2,3,0,0,6,0,0"
85,3,2020-03-10 12:04:13,"8,1,6,2","1,1,0,0,0,1,0,1","1,1,1,1","1583838250738,1583838251505,1583838252146,1583...",1583838249573,3869,"1,2,0,0,0,6,0,8"
86,3,2020-03-10 12:04:17,"8,4,5","0,0,0,1,1,0,0,1","1,1,1","1583838254802,1583838255649,1583838256394",1583838253707,3823,"0,0,0,4,5,0,0,8"

# Defining the strategies:

1. d.a.c. : Click as many times as possible
2. Rotation: make 1 firgure, rotate it 4 times, next figure
3. Subpar: Does not understand the objective at hand                       M + M‚Üª
4. Additive: Add 1 more line to your figure untill it is completely filled   R
5. substractive: Remove 1 line until you have 1 or 0 left                    R
6. Single: click 1 line until all 8 lines make 8 different figures           M 

we can make algorithms to see the difference between a machine learining program and the algorithm

## ‚öîÔ∏è 1. Divide and Conquer ‚öîÔ∏è
The student just submitted a lot of **CORRECT** answers very quickly less than 2.5 seconds per figure.

In [22]:
#code here

## üîÅ 2. Rotation üîÅ
The student chose **1** figure, rotated that 4 times and moved on to the next figure to do the same.

In [23]:
#code here

## 3. ü§™ Subpar: Does not understand the objective at hand ü§™
A lot of the same figure, a lot of clicks with no real results, very long time between figures etc.

In [24]:
def identify_strategy(actions):
    # Check if the value is a float or NaN
    if isinstance(actions, (float, int)):
        return "Invalid"  # Handle NaN or unexpected numeric values
    elif actions is None:
        return "Missing"  # Handle None or missing values
    else:
        unique_values = len(set(actions))
        if unique_values <= 2:
            return "Subpar"
        else:
            return "Advanced"
 #Apply the identify_strategy function to the 'numbercl' column and create a new 'strategy' column
pivot_df['strategy'] = pivot_df['numbercl'].apply(lambda x: identify_strategy(x))
pivot_df.head(50)

name,idll_vo3lv,timestamp,numbercl,patternsm,statuscl,timestampcl,timestampload,timestampsm,new_column,strategy
12,2,2020-10-01 09:52:14,"1,6,8,4,5,7,2,7,7,3","1,1,1,1,1,1,1,1","1,1,1,1,1,1,1,0,1,1","1601538723165,1601538724144,1601538725021,1601...",1601538721805,12106,"1,2,3,4,5,6,7,8",Advanced
13,2,2020-10-01 09:52:31,"6,8,4,1,2,7,8,5,8","1,1,0,1,1,1,1,1","1,1,1,1,1,1,0,1,1","1601538737663,1601538738454,1601538739815,1601...",1601538734066,17061,"1,2,0,4,5,6,7,8",Advanced
14,2,2020-10-01 09:52:40,"4,5,6,2","0,1,0,1,1,1,0,0","1,1,1,1","1601538755645,1601538756591,1601538757392,1601...",1601538751289,8516,"0,2,0,4,5,6,0,0",Advanced
15,2,2020-10-01 09:52:52,"3,8,7,5,5,8,5,6,8","0,0,1,0,1,1,1,1","1,1,1,1,0,0,1,1,1","1601538764144,1601538765306,1601538766035,1601...",1601538759972,12023,"0,0,3,0,5,6,7,8",Advanced
16,2,2020-10-01 09:52:58,"4,3,2,1","1,1,1,1,0,0,0,0","1,1,1,1","1601538773414,1601538774162,1601538775421,1601...",1601538772148,5470,"1,2,3,4,0,0,0,0",Advanced
17,2,2020-10-01 09:53:10,"8,7,6,2,3,3,3","0,1,1,0,0,1,1,1","1,1,1,1,1,0,1","1601538781442,1601538782939,1601538787197,1601...",1601538777799,12570,"0,2,3,0,0,6,7,8",Advanced
18,2,2020-10-01 09:53:16,"4,8,6,1,5","1,0,0,1,1,1,0,1","1,1,1,1,1","1601538791574,1601538792319,1601538793102,1601...",1601538790537,5034,"1,0,0,4,5,6,0,8",Advanced
19,2,2020-10-01 09:53:23,"7,3,2","0,1,1,0,0,0,1,0","1,1,1","1601538798418,1601538800316,1601538801321",1601538795840,7318,"0,2,3,0,0,0,7,0",Advanced
20,2,2020-10-01 09:53:28,"4,5,1","1,0,0,1,1,0,0,0","1,1,1","1601538805275,1601538806172,1601538807063",1601538803499,4793,"1,0,0,4,5,0,0,0",Advanced
21,2,2020-10-01 09:53:31,"8,6","0,0,0,0,0,1,0,1","1,1","1601538809428,1601538810415",1601538808458,2799,"0,0,0,0,0,6,0,8",Advanced
22,2,2020-10-01 09:53:39,"3,7,2,5,4,1","1,1,1,1,1,0,1,0","1,1,1,1,1,1","1601538812126,1601538812743,1601538813498,1601...",1601538811443,7813,"1,2,3,4,5,0,7,0",Advanced
23,2,2020-10-01 09:53:46,NaN,nan,NaN,"1601538820309,1601538821197,1601538821861,1601...",1601538819467,NaN,0,Invalid
24,2,2020-10-01 09:53:47,3,"0,0,1,0,0,0,0,0",1,1601538826435,1601538825694,1414,"0,0,3,0,0,0,0,0",Subpar
25,2,2020-10-01 09:53:49,7,"0,0,0,0,0,0,1,0",1,1601538828162,1601538827461,1498,"0,0,0,0,0,0,7,0",Subpar
26,2,2020-10-01 09:53:52,"[2, 2]","['0,1,0,0,0,0,0,0' '0,1,0,0,0,0,0,0']","[1, 1]","[1601538829928, 1601538829928]","[1601538829295, 1601538829295]","[2209, 2257]","0,2,0,0,0,0,0,0,9,0,0,0,0,0,0",Subpar
27,2,2020-10-01 09:53:59,8,"0,0,0,0,0,0,0,1",1,1601538832575,1601538831818,6712,"0,0,0,0,0,0,0,8",Subpar
28,2,2020-10-01 09:54:05,"6,3,3","0,0,0,0,0,1,0,0","1,1,0","1601538840305,1601538841370,1601538844020",1601538838784,6000,"0,0,0,0,0,6,0,0",Advanced
29,2,2020-10-01 09:54:08,"4,4,4","0,0,0,1,0,0,0,0","1,0,1","1601538845916,1601538845972,1601538846915",1601538844987,2889,"0,0,0,4,0,0,0,0",Subpar
30,2,2020-10-01 09:54:11,5,"0,0,0,0,1,0,0,0",1,1601538849579,1601538848323,2485,"0,0,0,0,5,0,0,0",Subpar
31,2,2020-10-01 09:54:14,1,"1,0,0,0,0,0,0,0",1,1601538852212,1601538851054,2966,"1,0,0,0,0,0,0,0",Subpar
32,2,2020-10-01 09:54:18,"5,7","0,0,0,0,1,0,1,0","1,1","1601538855845,1601538856887",1601538854280,3641,"0,0,0,0,5,0,7,0",Advanced
33,2,2020-10-01 09:54:22,"8,6","0,0,0,0,0,1,0,1","1,1","1601538860269,1601538861148",1601538858174,4136,"0,0,0,0,0,6,0,8",Advanced
34,2,2020-10-01 09:54:34,"1,3","1,0,1,0,0,0,0,0","1,1","1601538871202,1601538872759",1601538862573,11111,"1,0,3,0,0,0,0,0",Advanced
35,2,2020-10-01 09:54:38,"4,2","0,1,0,1,0,0,0,0","1,1","1601538875133,1601538876345",1601538873978,3438,"0,2,0,4,0,0,0,0",Advanced
36,2,2020-10-01 09:54:43,"8,7","0,0,0,0,0,0,1,1","1,1","1601538880678,1601538881468",1601538877718,5124,"0,0,0,0,0,0,7,8",Advanced
37,2,2020-10-01 09:54:49,"5,6","0,0,0,0,1,1,0,0","1,1","1601538884645,1601538885396",1601538883125,5422,"0,0,0,0,5,6,0,0",Advanced
38,2,2020-10-01 09:55:36,"4,1,2","1,1,0,1,0,0,0,0","1,1,1","1601538920982,1601538922686,1601538928204",1601538888820,44538,"1,2,0,4,0,0,0,0",Advanced
39,3,2020-03-10 12:01:09,"8,3","0,0,1,0,0,0,0,1","1,1","1583838068262,1583838069022",1583838066741,2970,"0,0,3,0,0,0,0,8",Advanced
40,3,2020-03-10 12:01:12,"6,1","1,0,0,0,0,1,0,0","1,1","1583838070926,1583838071430",1583838069787,2676,"1,0,0,0,0,6,0,0",Advanced
41,3,2020-03-10 12:01:15,"2,8","0,1,0,0,0,0,0,1","1,1","1583838073750,1583838074870",1583838072547,3115,"0,2,0,0,0,0,0,8",Advanced
42,3,2020-03-10 12:01:18,"4,5","0,0,0,1,1,0,0,0","1,1","1583838076598,1583838077046",1583838075754,2316,"0,0,0,4,5,0,0,0",Advanced
43,3,2020-03-10 12:01:21,"1,6","1,0,0,0,0,1,0,0","1,1","1583838079334,1583838080590",1583838078172,3730,"1,0,0,0,0,6,0,0",Advanced
44,3,2020-03-10 12:01:26,"5,7","0,0,0,0,1,0,1,0","1,1","1583838084934,1583838085694",1583838082005,4497,"0,0,0,0,5,0,7,0",Advanced
45,3,2020-03-10 12:01:29,"6,3","0,0,1,0,0,1,0,0","1,1","1583838087926,1583838088862",1583838086614,3064,"0,0,3,0,0,6,0,0",Advanced
46,3,2020-03-10 12:01:32,"4,5","0,0,0,1,1,0,0,0","1,1","1583838090886,1583838091390",1583838089766,2440,"0,0,0,4,5,0,0,0",Advanced
47,3,2020-03-10 12:01:35,"2,8","0,1,0,0,0,0,0,1","1,1","1583838093150,1583838094598",1583838092319,2895,"0,2,0,0,0,0,0,8",Advanced
48,3,2020-03-10 12:01:39,"1,3","1,0,1,0,0,0,0,0","1,1","1583838098046,1583838098845",1583838095342,3888,"1,0,3,0,0,0,0,0",Advanced
49,3,2020-03-10 12:01:43,"2,4","0,1,0,1,0,0,0,0","1,1","1583838101317,1583838102149",1583838099345,3749,"0,2,0,4,0,0,0,0",Advanced
50,3,2020-03-10 12:01:46,"5,6","0,0,0,0,1,1,0,0","1,1","1583838104750,1583838105581",1583838103201,3077,"0,0,0,0,5,6,0,0",Advanced
51,3,2020-03-10 12:01:50,"1,6","1,0,0,0,0,1,0,0","1,1","1583838108581,1583838109325",1583838106389,3729,"1,0,0,0,0,6,0,0",Advanced
52,3,2020-03-10 12:01:54,"2,4","0,1,0,1,0,0,0,0","1,1","1583838110893,1583838113597",1583838110241,4565,"0,2,0,4,0,0,0,0",Advanced
53,3,2020-03-10 12:01:59,"1,5,3,7","1,0,1,0,1,0,1,0","1,1,1,1","1583838115933,1583838116645,1583838118341,1583...",1583838114932,4826,"1,0,3,0,5,0,7,0",Advanced
54,3,2020-03-10 12:02:09,"2,4,8,6,8,7,8,5","0,1,0,1,1,1,1,1","1,1,1,1,0,1,1,1","1583838120957,1583838122645,1583838123733,1583...",1583838119901,9080,"0,2,0,4,5,6,7,8",Advanced
55,3,2020-03-10 12:02:13,"3,8,1,6,5","1,0,1,0,1,1,0,1","1,1,1,1,1","1583838129589,1583838130397,1583838131268,1583...",1583838129094,4655,"1,0,3,0,5,6,0,8",Advanced
56,3,2020-03-10 12:02:16,"2,8,5","0,1,0,0,1,0,0,1","1,1,1","1583838134725,1583838135309,1583838136245",1583838133937,2948,"0,2,0,0,5,0,0,8",Advanced
57,3,2020-03-10 12:02:25,"6,4,5,1,3,7,2","1,1,1,1,1,1,1,0","1,1,1,1,1,1,1","1583838138445,1583838139620,1583838140381,1583...",1583838137018,8027,"1,2,3,4,5,6,7,0",Advanced
58,3,2020-03-10 12:02:34,"8,8,4,5,1,6,2,3,7,8","1,1,1,1,1,1,1,1","1,0,1,1,1,1,1,1,1,1","1583838146060,1583838146716,1583838147428,1583...",1583838145183,9150,"1,2,3,4,5,6,7,8",Advanced
59,3,2020-03-10 12:02:36,"6,5","0,0,0,0,1,1,0,0","1,1","1583838155332,1583838156124",1583838154488,2388,"0,0,0,0,5,6,0,0",Advanced
60,3,2020-03-10 12:02:40,"1,2,6,7","1,1,0,0,0,1,1,0","1,1,1,1","1583838157692,1583838158348,1583838158820,1583...",1583838157058,3082,"1,2,0,0,0,6,7,0",Advanced
61,3,2020-03-10 12:02:43,"3,8,5,7","0,0,1,0,1,0,1,1","1,1,1,1","1583838160892,1583838161412,1583838161924,1583...",1583838160291,2705,"0,0,3,0,5,0,7,8",Advanced

## ‚ûï 4. Additive: Add 1 more line to your figure untill it is completely filled ‚ûï
start with one line and add moe and more untill your figure is completely filled

In [25]:
# get all the patterns a student made into an array

#after every "for" imagine that "each" follows
Students_who_are_adders = []
patterns = []
students = []

student_id_list = Dataset['idll_vo3lv'].unique().tolist() #This is the list af all the student IDs
student_pattern_list = [] #This will have all the patterns of all the students and be filled with student_patterns

for idll_vo3lv in student_id_list:
    student_patterns = []
    for pattern in Dataset['patternsm']:
        student_patterns.append(pattern)
    student_pattern_list.append(student_patterns)
student_pattern_list

KeyboardInterrupt:

In [ ]:
def adder(pattern, previous_pattern):
    """
    This function takes a pattern and its predecessor as input and returns True if the pattern is additive, False otherwise.
    """
    



    if pattern.size== previous_pattern.size + 1:
        #if pattern contains the same numbers in the same spots as previous_pattern, plus one more number in the end
        return True
    return False

In [ ]:
# for each student, (index in array 1) check if the pattern they made is the same as the one before +1
checkcount = 0
previous_pattern = 0,0,0,0,0,0,0,0
for student_patterns in student_pattern_list:
    for pattern in student_patterns:
        if checkcount == 5:
            students_who_are_adders.append(idll_vo3lv)
        if adder(pattern, previous_pattern):
            checkcount+=1
        else:
            checkcount = 0
        previous_pattern = pattern

AttributeError: 'str' object has no attribute 'size'

In [ ]:
input_string = '1,0,0,1,1,0,0,0'

'1,0,0,4,5,0,0,0'

## ‚ûñ 5. substractive: Remove 1 line until you have 1 or 0 left ‚ûñ
Start with a complec figure and remove lines untill there is 1 or none left.

In [29]:
# Function to remove lines iteratively
def subtractive_strategy(lines):
    if pd.isna(lines):
        return []

    line_list = list(map(int, lines.split(',')))
    result = []

    # Iterative removal of lines
    for i in range(len(line_list)):
        current_lines = line_list[:i] + line_list[i+1:]
        result.append(','.join(map(str, current_lines)))

    return result

# Apply subtractive strategy to each row in the 'patternsm' column
Dataset['subtractive_strategy'] = Dataset['patternsm'].apply(subtractive_strategy)

# Display the resulting DataFrame
print(Dataset[['idll_vo3lv', 'patternsm', 'subtractive_strategy']])

ValueError: invalid literal for int() with base 10: 'nan'

## ü¶Ü-d 6. Single: click 1 line until all 8 lines make 8 different figures 1Ô∏è üê≠
Different figures with one line each

In [ ]:
import pandas as pd
import numpy as np

# Function to parse 'patternsm' column
def parse_patternsm(x):
    return list(map(int, x.split(','))) if pd.notna(x) else []

# Function to check if all figures are unique in a list
def has_unique_figures(lst):
    return len(set(lst)) == len(lst)

# Function to check if all elements in the arrays are the same
def all_elements_same(arr):
    return all(x == arr[0] for x in arr)

# Function to identify strategy
def identify_strategy(row):
    pattern_list = parse_patternsm(row['patternsm'])
    number_array = np.array(list(map(int, row['numbercl'].split(',')))) if pd.notna(row['numbercl']) else []
    status_array = np.array(list(map(int, row['statuscl'].split(',')))) if pd.notna(row['statuscl']) else []
    timestamp_array = np.array(list(map(int, row['timestampcl'].split(',')))) if pd.notna(row['timestampcl']) else []

    if has_unique_figures(pattern_list):
        if all_elements_same(number_array) and all_elements_same(status_array) and all_elements_same(timestamp_array):
            return 'Single: click 1 line until all 8 lines make 8 different figures'
        else:
            return 'Unique Figures'
    else:
        return 'Not Unique Figures'

# Apply the strategy identification function to create a 'Strategy' column
pivot_df['Strategy'] = pivot_df.apply(identify_strategy, axis=1)

# Displaying the DataFrame with the new 'Strategy' column
print(pivot_df[['idll_vo3lv', 'patternsm', 'Strategy']])

cluster

In [ ]:
import pandas as pd
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# Assuming pivot_df is your DataFrame
# Replace 'numbercl' with the correct column name
features_for_clustering = ['numbercl']

# Extract relevant features and fill NaN values with 0
X = pivot_df[features_for_clustering].fillna(0)

# Choose the number of clusters (you may need to experiment)
k_clusters = 3

# Apply K-Means clustering
kmeans = KMeans(n_clusters=k_clusters, random_state=42)
pivot_df['cluster'] = kmeans.fit_predict(X)

# Visualize clusters
plt.scatter(X, [0] * len(X), c=pivot_df['cluster'], cmap='viridis')
plt.xlabel('Number of Lines Clicked')
plt.title('Clustering of FPT Strategies')
plt.show()